"""
SQLAlchemy modeli za tablice rutiranja i arhive naloga.

Tablice:
  - nalozi_header_rutiranje: nalozi prebaceni za rutiranje
  - nalozi_details_rutiranje: stavke naloga u rutiranju
  - nalozi_header_arhiva: arhivirani nalozi (izvjestaji)
  - nalozi_details_arhiva: stavke arhiviranih naloga
"""

from sqlalchemy import (
    Column, String, Integer, Date, DateTime, Numeric, Text, func, ForeignKey
)

from app.db.base import Base


class NalogHeaderRutiranje(Base):
    """Nalog prebačen u rutiranje — čeka kreiranje rute."""
    __tablename__ = "nalozi_header_rutiranje"

    nalog_prodaje_uid = Column(String(50), primary_key=True)
    nalog_prodaje_b2b = Column(String(50), nullable=True)
    broj = Column(Integer, nullable=True)
    datum = Column(Date, nullable=True)
    rezervacija_od_datuma = Column(DateTime, nullable=True)
    rezervacija_do_datuma = Column(Date, nullable=True)
    raspored = Column(Date, nullable=True)
    skladiste = Column(String(50), nullable=True)
    skladiste_b2b = Column(String(50), nullable=True)
    na__skladiste = Column(String(50), nullable=True)
    na__skladiste_b2b = Column(String(50), nullable=True)
    partner_uid = Column(String(50), nullable=True)
    partner = Column(String(50), nullable=True)
    partner_b2b = Column(String(50), nullable=True)
    korisnik__partner_uid = Column(String(50), nullable=True)
    korisnik__partner = Column(String(50), nullable=True)
    korisnik__partner_b2b = Column(String(50), nullable=True)
    agent__partner_uid = Column(String(50), nullable=True)
    agent__partner = Column(String(50), nullable=True)
    agent__partner_b2b = Column(String(50), nullable=True)
    narudzba = Column(String(100), nullable=True)
    kupac_placa_isporuku = Column(String(1), nullable=True)
    valuta = Column(String(10), nullable=True)
    valuta_b2b = Column(String(50), nullable=True)
    tecaj = Column(Numeric(18, 6), nullable=True)
    generalni_rabat = Column(String(50), nullable=True)
    placa_porez = Column(String(1), nullable=True)
    cassa_sconto = Column(String(1), nullable=True)
    poruka_gore = Column(Text, nullable=True)
    poruka_dolje = Column(Text, nullable=True)
    napomena = Column(Text, nullable=True)
    na_uvid = Column(String(50), nullable=True)
    referenca_isporuke = Column(String(100), nullable=True)
    sa__skladiste = Column(String(50), nullable=True)
    sa__skladiste_b2b = Column(String(50), nullable=True)
    skl_dokument = Column(String(10), nullable=True)
    skl_dokument_b2b = Column(String(50), nullable=True)
    status = Column(String(20), nullable=True)
    status_b2b = Column(String(50), nullable=True)
    komercijalist__radnik = Column(String(100), nullable=True)
    komercijalist__radnik_b2b = Column(String(50), nullable=True)
    dostavljac_uid = Column(String(50), nullable=True)
    dostavljac__radnik = Column(String(100), nullable=True)
    dostavljac__radnik_b2b = Column(String(50), nullable=True)
    kreirao__radnik_uid = Column(String(50), nullable=True)
    kreirao__radnik = Column(String(100), nullable=True)
    kreirao__radnik_ime = Column(String(255), nullable=True)
    vrsta_isporuke = Column(String(50), nullable=True)
    vrsta_isporuke_b2b = Column(String(50), nullable=True)
    izravna_dostava = Column(String(1), nullable=True)
    dropoff_sifra = Column(String(50), nullable=True)
    dropoff_naziv = Column(String(255), nullable=True)
    user_uid = Column(String(50), nullable=True)
    username = Column(String(100), nullable=True)
    user_b2b = Column(String(50), nullable=True)
    tip_racuna_uid = Column(String(50), nullable=True)
    tip_racuna = Column(String(20), nullable=True)
    tip_racuna_b2b = Column(String(50), nullable=True)
    predmet_uid = Column(String(50), nullable=True)
    predmet = Column(String(50), nullable=True)
    predmet_b2b = Column(String(50), nullable=True)
    za_naplatu = Column(Numeric(18, 2), nullable=True)
    zki = Column(String(100), nullable=True)
    jir = Column(String(100), nullable=True)
    regija_id = Column(Integer, nullable=True)
    vozilo_tip = Column(String(50), nullable=True)
    total_weight = Column(Numeric(18, 3), nullable=True)
    total_volume = Column(Numeric(18, 6), nullable=True)
    synced_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.getutcdate())
    updated_at = Column(DateTime, server_default=func.getutcdate(), onupdate=func.getutcdate())
    # Dodatne kolone za rutiranje
    ruta_id = Column(Integer, nullable=True)
    status_rutiranja = Column(String(30), nullable=False, server_default="CEKA_RUTU")
    prebaceno_at = Column(DateTime, server_default=func.getutcdate())
    manual_paleta = Column(Integer, nullable=True)


class NalogDetailRutiranje(Base):
    """Stavka naloga u rutiranju."""
    __tablename__ = "nalozi_details_rutiranje"

    stavka_uid = Column(String(50), primary_key=True)
    nalog_prodaje_uid = Column(
        String(50),
        ForeignKey("nalozi_header_rutiranje.nalog_prodaje_uid", ondelete="CASCADE"),
        nullable=False,
    )
    artikl = Column(String(50), nullable=True)
    artikl_uid = Column(String(50), nullable=True)
    artikl_b2b = Column(String(50), nullable=True)
    mjesto_troska = Column(String(50), nullable=True)
    mjesto_troska_uid = Column(String(50), nullable=True)
    mjesto_troska_b2b = Column(String(50), nullable=True)
    predmet = Column(String(50), nullable=True)
    predmet_uid = Column(String(50), nullable=True)
    predmet_b2b = Column(String(50), nullable=True)
    opis = Column(Text, nullable=True)
    kolicina = Column(Numeric(18, 3), nullable=True)
    pakiranja = Column(Numeric(18, 3), nullable=True)
    cijena = Column(Numeric(18, 2), nullable=True)
    detaljni_opis = Column(String(1), nullable=True)
    specifikacija = Column(Text, nullable=True)
    rabat = Column(Numeric(18, 2), nullable=True)
    dodatni_rabat = Column(String(50), nullable=True)
    redoslijed = Column(Integer, nullable=True)
    synced_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.getutcdate())
    updated_at = Column(DateTime, server_default=func.getutcdate(), onupdate=func.getutcdate())


class NalogHeaderArhiva(Base):
    """Arhivirani nalog — sadrži kompletne podatke o dostavi za izvještaje."""
    __tablename__ = "nalozi_header_arhiva"

    id = Column(Integer, primary_key=True, autoincrement=True)
    nalog_prodaje_uid = Column(String(50), nullable=False)
    nalog_prodaje_b2b = Column(String(50), nullable=True)
    broj = Column(Integer, nullable=True)
    datum = Column(Date, nullable=True)
    rezervacija_od_datuma = Column(DateTime, nullable=True)
    rezervacija_do_datuma = Column(Date, nullable=True)
    raspored = Column(Date, nullable=True)
    skladiste = Column(String(50), nullable=True)
    skladiste_b2b = Column(String(50), nullable=True)
    na__skladiste = Column(String(50), nullable=True)
    na__skladiste_b2b = Column(String(50), nullable=True)
    partner_uid = Column(String(50), nullable=True)
    partner = Column(String(50), nullable=True)
    partner_b2b = Column(String(50), nullable=True)
    korisnik__partner_uid = Column(String(50), nullable=True)
    korisnik__partner = Column(String(50), nullable=True)
    korisnik__partner_b2b = Column(String(50), nullable=True)
    agent__partner_uid = Column(String(50), nullable=True)
    agent__partner = Column(String(50), nullable=True)
    agent__partner_b2b = Column(String(50), nullable=True)
    narudzba = Column(String(100), nullable=True)
    kupac_placa_isporuku = Column(String(1), nullable=True)
    valuta = Column(String(10), nullable=True)
    valuta_b2b = Column(String(50), nullable=True)
    tecaj = Column(Numeric(18, 6), nullable=True)
    generalni_rabat = Column(String(50), nullable=True)
    placa_porez = Column(String(1), nullable=True)
    cassa_sconto = Column(String(1), nullable=True)
    poruka_gore = Column(Text, nullable=True)
    poruka_dolje = Column(Text, nullable=True)
    napomena = Column(Text, nullable=True)
    na_uvid = Column(String(50), nullable=True)
    referenca_isporuke = Column(String(100), nullable=True)
    sa__skladiste = Column(String(50), nullable=True)
    sa__skladiste_b2b = Column(String(50), nullable=True)
    skl_dokument = Column(String(10), nullable=True)
    skl_dokument_b2b = Column(String(50), nullable=True)
    status = Column(String(20), nullable=True)
    status_b2b = Column(String(50), nullable=True)
    komercijalist__radnik = Column(String(100), nullable=True)
    komercijalist__radnik_b2b = Column(String(50), nullable=True)
    dostavljac_uid = Column(String(50), nullable=True)
    dostavljac__radnik = Column(String(100), nullable=True)
    dostavljac__radnik_b2b = Column(String(50), nullable=True)
    kreirao__radnik_uid = Column(String(50), nullable=True)
    kreirao__radnik = Column(String(100), nullable=True)
    kreirao__radnik_ime = Column(String(255), nullable=True)
    vrsta_isporuke = Column(String(50), nullable=True)
    vrsta_isporuke_b2b = Column(String(50), nullable=True)
    izravna_dostava = Column(String(1), nullable=True)
    dropoff_sifra = Column(String(50), nullable=True)
    dropoff_naziv = Column(String(255), nullable=True)
    user_uid = Column(String(50), nullable=True)
    username = Column(String(100), nullable=True)
    user_b2b = Column(String(50), nullable=True)
    tip_racuna_uid = Column(String(50), nullable=True)
    tip_racuna = Column(String(20), nullable=True)
    tip_racuna_b2b = Column(String(50), nullable=True)
    predmet_uid = Column(String(50), nullable=True)
    predmet = Column(String(50), nullable=True)
    predmet_b2b = Column(String(50), nullable=True)
    za_naplatu = Column(Numeric(18, 2), nullable=True)
    zki = Column(String(100), nullable=True)
    jir = Column(String(100), nullable=True)
    regija_id = Column(Integer, nullable=True)
    vozilo_tip = Column(String(50), nullable=True)
    total_weight = Column(Numeric(18, 3), nullable=True)
    total_volume = Column(Numeric(18, 6), nullable=True)
    synced_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    # Podaci o ruti
    ruta_id = Column(Integer, nullable=True)
    ruta_datum = Column(Date, nullable=True)
    ruta_algoritam = Column(String(50), nullable=True)
    vozilo_id = Column(Integer, nullable=True)
    vozilo_oznaka = Column(String(100), nullable=True)
    vozac_id = Column(Integer, nullable=True)
    vozac_ime = Column(String(200), nullable=True)
    # Podaci o dostavi
    redoslijed_dostave = Column(Integer, nullable=True)
    eta = Column(DateTime, nullable=True)
    vrijeme_dostave = Column(DateTime, nullable=True)
    status_dostave = Column(String(30), nullable=True)
    razlog_nedostave = Column(String(500), nullable=True)
    napomena_dostave = Column(Text, nullable=True)
    gps_lat_dostave = Column(Numeric(18, 8), nullable=True)
    gps_lng_dostave = Column(Numeric(18, 8), nullable=True)
    # Statistika rute
    distance_od_prethodnog_km = Column(Numeric(18, 3), nullable=True)
    trajanje_od_prethodnog_min = Column(Integer, nullable=True)
    ukupna_distance_rute_km = Column(Numeric(18, 3), nullable=True)
    ukupno_trajanje_rute_min = Column(Integer, nullable=True)
    broj_stopova_na_ruti = Column(Integer, nullable=True)
    # Meta
    arhivirano_at = Column(DateTime, server_default=func.getutcdate())


class NalogDetailArhiva(Base):
    """Stavka arhiviranog naloga."""
    __tablename__ = "nalozi_details_arhiva"

    id = Column(Integer, primary_key=True, autoincrement=True)
    arhiva_header_id = Column(
        Integer,
        ForeignKey("nalozi_header_arhiva.id", ondelete="CASCADE"),
        nullable=False,
    )
    stavka_uid = Column(String(50), nullable=False)
    nalog_prodaje_uid = Column(String(50), nullable=False)
    artikl = Column(String(50), nullable=True)
    artikl_uid = Column(String(50), nullable=True)
    artikl_b2b = Column(String(50), nullable=True)
    mjesto_troska = Column(String(50), nullable=True)
    mjesto_troska_uid = Column(String(50), nullable=True)
    mjesto_troska_b2b = Column(String(50), nullable=True)
    predmet = Column(String(50), nullable=True)
    predmet_uid = Column(String(50), nullable=True)
    predmet_b2b = Column(String(50), nullable=True)
    opis = Column(Text, nullable=True)
    kolicina = Column(Numeric(18, 3), nullable=True)
    pakiranja = Column(Numeric(18, 3), nullable=True)
    cijena = Column(Numeric(18, 2), nullable=True)
    detaljni_opis = Column(String(1), nullable=True)
    specifikacija = Column(Text, nullable=True)
    rabat = Column(Numeric(18, 2), nullable=True)
    dodatni_rabat = Column(String(50), nullable=True)
    redoslijed = Column(Integer, nullable=True)
    synced_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    arhivirano_at = Column(DateTime, server_default=func.getutcdate())
